### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by LGA1150** [LGA1150/openwrt-tinyfecvpn#1]
@wangyu- 
尝试运行动态编译的 0820 版 tinyfecVPN 时出现以下错误
```
Assertion failed: ("libev: ev_signal_start called with illegal signal number", w->signum > 0 && w->signum < EV_NSIG) (ev.c: ev_signal_start: 4078)
Aborted
```

**Comment by wangyu-** [comment]
动态编译版有没有办法稳定复现？

用release里的0820静态编译版，是否可以复现？

**Comment by LGA1150** [comment]
一运行就会出现
为了通过编译，我把 `UDPspeeder/my_ev.cpp` 的 `ev.c` 改为 `ev.h` （为什么要 include 源文件？)，是否与这个有关？

**Comment by wangyu-** [comment]
>为了通过编译，我把 UDPspeeder/my_ev.cpp 的 ev.c 改为 ev.h （为什么要 include 源文件？)，是否与这个有关？

非常有关

include源文件只是不常见，libev STANDALONE模式就是这样用的

默认代码可以动态编译通过，不需要改。

**Comment by LGA1150** [comment]
添加 `-IUDPspeeder/libev` 后，可以找到 `ev.c` 了，目前正常运行

**Comment by LGA1150** [comment]
@wangyu- 
另一个问题：STANDALONE 模式意味着 libev 被静态编译进去了吗

**Comment by wangyu-** [comment]
STANDALONE相当于把libev的代码作为源文件嵌入到了你的项目里，严格来说跟静态/非静态编译说的不是一回事。类似于静态编译进去了。

**Comment by LGA1150** [comment]
如果使用非 STANDALONE 模式，要怎么修改？

**Comment by wangyu-** [comment]
大概是：编译libev动态版，去掉my_ev.cpp my_ev.h my_ev_common.h这3个文件，直接include ev.h。

细节参考libev官方文档。

**Comment by LGA1150** [comment]
我去掉了 `my_ev.cpp my_ev_common.h` ，把 `my_ev.h` 里的 `#include "my_ev_common.h"` 一行删除，编译时出现 `'ev_loop' does not name a type` 错误
